//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaconographyPortable.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaconographyPortable.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;kind&quot;:&quot;Listing&quot;,
        ///  &quot;data&quot;:{
        ///    &quot;modhash&quot;:&quot;&quot;,
        ///    &quot;children&quot;:[
        ///      {
        ///        &quot;kind&quot;:&quot;t5&quot;,
        ///        &quot;data&quot;:{
        ///          &quot;display_name&quot;:&quot;funny&quot;,
        ///          &quot;description&quot;:&quot;### [Results of the facebook poll](http://www.reddit.com/r/funny/comments/11yjak/the_results_of_the_facebook_poll/)\n\n\n\n### Reminder: Political posts are not permitted in /r/funny. Try [/r/PoliticalHumor](/r/PoliticalHumor) instead!\n\n\n\n**NEW!** No gore or porn (including sexually graphic images). Other NSFW content must b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultSubreddits1 {
            get {
                return ResourceManager.GetString("DefaultSubreddits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;kind&quot;:&quot;t5&quot;,
        ///        &quot;data&quot;:{
        ///          &quot;display_name&quot;:&quot;WTF&quot;,
        ///          &quot;description&quot;:&quot;**New Rules**:\n\n* **No screenshots (e.g. Facebook, Youtube)**\n* No memes, captioned images.\n* No rage comics\n* No [politics / posts with political implications](http://www.reddit.com/r/WTF/comments/eysc5/do_not_post_any_politics_to_rwtf_period_no/) - Includes Activism, Call for public outcry etc.\n* No re-hosted web comics\n* No begging for upvotes\n* No links to reddit\n* Personal information is not al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultSubreddits2 {
            get {
                return ResourceManager.GetString("DefaultSubreddits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;kind&quot;:&quot;t5&quot;,
        ///        &quot;data&quot;:{
        ///          &quot;display_name&quot;:&quot;AdviceAnimals&quot;,
        ///          &quot;description&quot;:&quot;######[AA&apos;s Official Position on Reddit Drama, Please Post Accordingly](http://i.imgur.com/Q3KeD.jpg)\n\nWelcome to r/AdviceAnimals\n=====================\n\n\n###Sound advice from ~~animals~~ anything!\n\n\n[](/techduck) [](/techduck)  [](/techduck)  [](/techduck \&quot;\&quot;)  Rules [](/techduck) [](/techduck) [](/techduck) [](/techduck) \n====\n- We&apos;re here to have a laugh, don&apos;t get too serious.\n\n- F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultSubreddits3 {
            get {
                return ResourceManager.GetString("DefaultSubreddits3", resourceCulture);
            }
        }
    }
}
